#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DestructionReport
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Payazob")]
	public partial class DataClasses_DestractionReportDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertmDestructionReport(mDestructionReport instance);
    partial void UpdatemDestructionReport(mDestructionReport instance);
    partial void DeletemDestructionReport(mDestructionReport instance);
    #endregion
		
		public DataClasses_DestractionReportDataContext() : 
				base(global::DAL.Properties.Settings.Default.PayazobConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_DestractionReportDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_DestractionReportDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_DestractionReportDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_DestractionReportDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<mDestructionReport> mDestructionReports
		{
			get
			{
				return this.GetTable<mDestructionReport>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mDestructionReport")]
	public partial class mDestructionReport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _x_;
		
		private string _xDate;
		
		private System.Nullable<int> _xShift_;
		
		private string _xDateProduction;
		
		private System.Nullable<int> _xPiceces_;
		
		private System.Nullable<int> _xCount;
		
		private string _xGrindingPlace;
		
		private System.Nullable<decimal> _xDepth;
		
		private System.Nullable<bool> _xResult;
		
		private string _xComment;
		
		private System.Nullable<int> _xApprove_;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onx_Changing(int value);
    partial void Onx_Changed();
    partial void OnxDateChanging(string value);
    partial void OnxDateChanged();
    partial void OnxShift_Changing(System.Nullable<int> value);
    partial void OnxShift_Changed();
    partial void OnxDateProductionChanging(string value);
    partial void OnxDateProductionChanged();
    partial void OnxPiceces_Changing(System.Nullable<int> value);
    partial void OnxPiceces_Changed();
    partial void OnxCountChanging(System.Nullable<int> value);
    partial void OnxCountChanged();
    partial void OnxGrindingPlaceChanging(string value);
    partial void OnxGrindingPlaceChanged();
    partial void OnxDepthChanging(System.Nullable<decimal> value);
    partial void OnxDepthChanged();
    partial void OnxResultChanging(System.Nullable<bool> value);
    partial void OnxResultChanged();
    partial void OnxCommentChanging(string value);
    partial void OnxCommentChanged();
    partial void OnxApprove_Changing(System.Nullable<int> value);
    partial void OnxApprove_Changed();
    #endregion
		
		public mDestructionReport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_x_", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int x_
		{
			get
			{
				return this._x_;
			}
			set
			{
				if ((this._x_ != value))
				{
					this.Onx_Changing(value);
					this.SendPropertyChanging();
					this._x_ = value;
					this.SendPropertyChanged("x_");
					this.Onx_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xDate", DbType="Char(10)")]
		public string xDate
		{
			get
			{
				return this._xDate;
			}
			set
			{
				if ((this._xDate != value))
				{
					this.OnxDateChanging(value);
					this.SendPropertyChanging();
					this._xDate = value;
					this.SendPropertyChanged("xDate");
					this.OnxDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xShift_", DbType="Int")]
		public System.Nullable<int> xShift_
		{
			get
			{
				return this._xShift_;
			}
			set
			{
				if ((this._xShift_ != value))
				{
					this.OnxShift_Changing(value);
					this.SendPropertyChanging();
					this._xShift_ = value;
					this.SendPropertyChanged("xShift_");
					this.OnxShift_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xDateProduction", DbType="Char(10)")]
		public string xDateProduction
		{
			get
			{
				return this._xDateProduction;
			}
			set
			{
				if ((this._xDateProduction != value))
				{
					this.OnxDateProductionChanging(value);
					this.SendPropertyChanging();
					this._xDateProduction = value;
					this.SendPropertyChanged("xDateProduction");
					this.OnxDateProductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xPiceces_", DbType="Int")]
		public System.Nullable<int> xPiceces_
		{
			get
			{
				return this._xPiceces_;
			}
			set
			{
				if ((this._xPiceces_ != value))
				{
					this.OnxPiceces_Changing(value);
					this.SendPropertyChanging();
					this._xPiceces_ = value;
					this.SendPropertyChanged("xPiceces_");
					this.OnxPiceces_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xCount", DbType="Int")]
		public System.Nullable<int> xCount
		{
			get
			{
				return this._xCount;
			}
			set
			{
				if ((this._xCount != value))
				{
					this.OnxCountChanging(value);
					this.SendPropertyChanging();
					this._xCount = value;
					this.SendPropertyChanged("xCount");
					this.OnxCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xGrindingPlace", DbType="NVarChar(50)")]
		public string xGrindingPlace
		{
			get
			{
				return this._xGrindingPlace;
			}
			set
			{
				if ((this._xGrindingPlace != value))
				{
					this.OnxGrindingPlaceChanging(value);
					this.SendPropertyChanging();
					this._xGrindingPlace = value;
					this.SendPropertyChanged("xGrindingPlace");
					this.OnxGrindingPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xDepth", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> xDepth
		{
			get
			{
				return this._xDepth;
			}
			set
			{
				if ((this._xDepth != value))
				{
					this.OnxDepthChanging(value);
					this.SendPropertyChanging();
					this._xDepth = value;
					this.SendPropertyChanged("xDepth");
					this.OnxDepthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xResult", DbType="Bit")]
		public System.Nullable<bool> xResult
		{
			get
			{
				return this._xResult;
			}
			set
			{
				if ((this._xResult != value))
				{
					this.OnxResultChanging(value);
					this.SendPropertyChanging();
					this._xResult = value;
					this.SendPropertyChanged("xResult");
					this.OnxResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xComment", DbType="NVarChar(500)")]
		public string xComment
		{
			get
			{
				return this._xComment;
			}
			set
			{
				if ((this._xComment != value))
				{
					this.OnxCommentChanging(value);
					this.SendPropertyChanging();
					this._xComment = value;
					this.SendPropertyChanged("xComment");
					this.OnxCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xApprove_", DbType="Int")]
		public System.Nullable<int> xApprove_
		{
			get
			{
				return this._xApprove_;
			}
			set
			{
				if ((this._xApprove_ != value))
				{
					this.OnxApprove_Changing(value);
					this.SendPropertyChanging();
					this._xApprove_ = value;
					this.SendPropertyChanged("xApprove_");
					this.OnxApprove_Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
