//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name appcode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroup", ReplyAction="*")]
        BLL.ServiceReference1.getgroupResponse getgroup(BLL.ServiceReference1.getgroupRequest request);
        
        // CODEGEN: Generating message contract since element name appcode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getmobilebulk", ReplyAction="*")]
        BLL.ServiceReference1.getmobilebulkResponse getmobilebulk(BLL.ServiceReference1.getmobilebulkRequest request);
        
        // CODEGEN: Generating message contract since element name appcode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupstr", ReplyAction="*")]
        BLL.ServiceReference1.getgroupstrResponse getgroupstr(BLL.ServiceReference1.getgroupstrRequest request);
        
        // CODEGEN: Generating message contract since element name groupid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupmobiles", ReplyAction="*")]
        BLL.ServiceReference1.getgroupmobilesResponse getgroupmobiles(BLL.ServiceReference1.getgroupmobilesRequest request);
        
        // CODEGEN: Generating message contract since element name groupid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupmobilesstr", ReplyAction="*")]
        BLL.ServiceReference1.getgroupmobilesstrResponse getgroupmobilesstr(BLL.ServiceReference1.getgroupmobilesstrRequest request);
        
        // CODEGEN: Generating message contract since element name groupid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupcount", ReplyAction="*")]
        BLL.ServiceReference1.getgroupcountResponse getgroupcount(BLL.ServiceReference1.getgroupcountRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        BLL.ServiceReference1.SendSMSResponse SendSMS(BLL.ServiceReference1.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemainSms", ReplyAction="*")]
        BLL.ServiceReference1.RemainSmsResponse RemainSms(BLL.ServiceReference1.RemainSmsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send1sms", ReplyAction="*")]
        BLL.ServiceReference1.Send1smsResponse Send1sms(BLL.ServiceReference1.Send1smsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send1Bulk", ReplyAction="*")]
        BLL.ServiceReference1.Send1BulkResponse Send1Bulk(BLL.ServiceReference1.Send1BulkRequest request);
        
        // CODEGEN: Generating message contract since element name cityid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getcitymobiles", ReplyAction="*")]
        BLL.ServiceReference1.getcitymobilesResponse getcitymobiles(BLL.ServiceReference1.getcitymobilesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroup", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getgroupRequestBody Body;
        
        public getgroupRequest() {
        }
        
        public getgroupRequest(BLL.ServiceReference1.getgroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appcode;
        
        public getgroupRequestBody() {
        }
        
        public getgroupRequestBody(string appcode) {
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getgroupResponseBody Body;
        
        public getgroupResponse() {
        }
        
        public getgroupResponse(BLL.ServiceReference1.getgroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupResult;
        
        public getgroupResponseBody() {
        }
        
        public getgroupResponseBody(string getgroupResult) {
            this.getgroupResult = getgroupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getmobilebulkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getmobilebulk", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getmobilebulkRequestBody Body;
        
        public getmobilebulkRequest() {
        }
        
        public getmobilebulkRequest(BLL.ServiceReference1.getmobilebulkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getmobilebulkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string postcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string citycode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mode;
        
        public getmobilebulkRequestBody() {
        }
        
        public getmobilebulkRequestBody(string appcode, string postcode, string citycode, string mode) {
            this.appcode = appcode;
            this.postcode = postcode;
            this.citycode = citycode;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getmobilebulkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getmobilebulkResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getmobilebulkResponseBody Body;
        
        public getmobilebulkResponse() {
        }
        
        public getmobilebulkResponse(BLL.ServiceReference1.getmobilebulkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getmobilebulkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getmobilebulkResult;
        
        public getmobilebulkResponseBody() {
        }
        
        public getmobilebulkResponseBody(string getmobilebulkResult) {
            this.getmobilebulkResult = getmobilebulkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupstrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupstr", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getgroupstrRequestBody Body;
        
        public getgroupstrRequest() {
        }
        
        public getgroupstrRequest(BLL.ServiceReference1.getgroupstrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupstrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appcode;
        
        public getgroupstrRequestBody() {
        }
        
        public getgroupstrRequestBody(string appcode) {
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupstrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupstrResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getgroupstrResponseBody Body;
        
        public getgroupstrResponse() {
        }
        
        public getgroupstrResponse(BLL.ServiceReference1.getgroupstrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupstrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupstrResult;
        
        public getgroupstrResponseBody() {
        }
        
        public getgroupstrResponseBody(string getgroupstrResult) {
            this.getgroupstrResult = getgroupstrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupmobilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupmobiles", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getgroupmobilesRequestBody Body;
        
        public getgroupmobilesRequest() {
        }
        
        public getgroupmobilesRequest(BLL.ServiceReference1.getgroupmobilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupmobilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appcode;
        
        public getgroupmobilesRequestBody() {
        }
        
        public getgroupmobilesRequestBody(string groupid, string appcode) {
            this.groupid = groupid;
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupmobilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupmobilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getgroupmobilesResponseBody Body;
        
        public getgroupmobilesResponse() {
        }
        
        public getgroupmobilesResponse(BLL.ServiceReference1.getgroupmobilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupmobilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupmobilesResult;
        
        public getgroupmobilesResponseBody() {
        }
        
        public getgroupmobilesResponseBody(string getgroupmobilesResult) {
            this.getgroupmobilesResult = getgroupmobilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupmobilesstrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupmobilesstr", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getgroupmobilesstrRequestBody Body;
        
        public getgroupmobilesstrRequest() {
        }
        
        public getgroupmobilesstrRequest(BLL.ServiceReference1.getgroupmobilesstrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupmobilesstrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appcode;
        
        public getgroupmobilesstrRequestBody() {
        }
        
        public getgroupmobilesstrRequestBody(string groupid, string appcode) {
            this.groupid = groupid;
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupmobilesstrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupmobilesstrResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getgroupmobilesstrResponseBody Body;
        
        public getgroupmobilesstrResponse() {
        }
        
        public getgroupmobilesstrResponse(BLL.ServiceReference1.getgroupmobilesstrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupmobilesstrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupmobilesstrResult;
        
        public getgroupmobilesstrResponseBody() {
        }
        
        public getgroupmobilesstrResponseBody(string getgroupmobilesstrResult) {
            this.getgroupmobilesstrResult = getgroupmobilesstrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupcountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupcount", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getgroupcountRequestBody Body;
        
        public getgroupcountRequest() {
        }
        
        public getgroupcountRequest(BLL.ServiceReference1.getgroupcountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupcountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appcode;
        
        public getgroupcountRequestBody() {
        }
        
        public getgroupcountRequestBody(string groupid, string appcode) {
            this.groupid = groupid;
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupcountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupcountResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getgroupcountResponseBody Body;
        
        public getgroupcountResponse() {
        }
        
        public getgroupcountResponse(BLL.ServiceReference1.getgroupcountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupcountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupcountResult;
        
        public getgroupcountResponseBody() {
        }
        
        public getgroupcountResponseBody(string getgroupcountResult) {
            this.getgroupcountResult = getgroupcountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(BLL.ServiceReference1.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobileno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pnlno;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(string username, string password, string text, string mobileno, string pnlno) {
            this.username = username;
            this.password = password;
            this.text = text;
            this.mobileno = mobileno;
            this.pnlno = pnlno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(BLL.ServiceReference1.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(string SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemainSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemainSms", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.RemainSmsRequestBody Body;
        
        public RemainSmsRequest() {
        }
        
        public RemainSmsRequest(BLL.ServiceReference1.RemainSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemainSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public RemainSmsRequestBody() {
        }
        
        public RemainSmsRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemainSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemainSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.RemainSmsResponseBody Body;
        
        public RemainSmsResponse() {
        }
        
        public RemainSmsResponse(BLL.ServiceReference1.RemainSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemainSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RemainSmsResult;
        
        public RemainSmsResponseBody() {
        }
        
        public RemainSmsResponseBody(string RemainSmsResult) {
            this.RemainSmsResult = RemainSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send1smsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send1sms", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.Send1smsRequestBody Body;
        
        public Send1smsRequest() {
        }
        
        public Send1smsRequest(BLL.ServiceReference1.Send1smsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send1smsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobileno;
        
        public Send1smsRequestBody() {
        }
        
        public Send1smsRequestBody(string username, string text, string mobileno) {
            this.username = username;
            this.text = text;
            this.mobileno = mobileno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send1smsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send1smsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.Send1smsResponseBody Body;
        
        public Send1smsResponse() {
        }
        
        public Send1smsResponse(BLL.ServiceReference1.Send1smsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send1smsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Send1smsResult;
        
        public Send1smsResponseBody() {
        }
        
        public Send1smsResponseBody(string Send1smsResult) {
            this.Send1smsResult = Send1smsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send1BulkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send1Bulk", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.Send1BulkRequestBody Body;
        
        public Send1BulkRequest() {
        }
        
        public Send1BulkRequest(BLL.ServiceReference1.Send1BulkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send1BulkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobileno;
        
        public Send1BulkRequestBody() {
        }
        
        public Send1BulkRequestBody(string username, string text, string mobileno) {
            this.username = username;
            this.text = text;
            this.mobileno = mobileno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send1BulkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send1BulkResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.Send1BulkResponseBody Body;
        
        public Send1BulkResponse() {
        }
        
        public Send1BulkResponse(BLL.ServiceReference1.Send1BulkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send1BulkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Send1BulkResult;
        
        public Send1BulkResponseBody() {
        }
        
        public Send1BulkResponseBody(string Send1BulkResult) {
            this.Send1BulkResult = Send1BulkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcitymobilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcitymobiles", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getcitymobilesRequestBody Body;
        
        public getcitymobilesRequest() {
        }
        
        public getcitymobilesRequest(BLL.ServiceReference1.getcitymobilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getcitymobilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cityid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int mode;
        
        public getcitymobilesRequestBody() {
        }
        
        public getcitymobilesRequestBody(string cityid, int mode) {
            this.cityid = cityid;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcitymobilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcitymobilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.ServiceReference1.getcitymobilesResponseBody Body;
        
        public getcitymobilesResponse() {
        }
        
        public getcitymobilesResponse(BLL.ServiceReference1.getcitymobilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getcitymobilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getcitymobilesResult;
        
        public getcitymobilesResponseBody() {
        }
        
        public getcitymobilesResponseBody(string getcitymobilesResult) {
            this.getcitymobilesResult = getcitymobilesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BLL.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BLL.ServiceReference1.ServiceSoap>, BLL.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.ServiceReference1.getgroupResponse BLL.ServiceReference1.ServiceSoap.getgroup(BLL.ServiceReference1.getgroupRequest request) {
            return base.Channel.getgroup(request);
        }
        
        public string getgroup(string appcode) {
            BLL.ServiceReference1.getgroupRequest inValue = new BLL.ServiceReference1.getgroupRequest();
            inValue.Body = new BLL.ServiceReference1.getgroupRequestBody();
            inValue.Body.appcode = appcode;
            BLL.ServiceReference1.getgroupResponse retVal = ((BLL.ServiceReference1.ServiceSoap)(this)).getgroup(inValue);
            return retVal.Body.getgroupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.ServiceReference1.getmobilebulkResponse BLL.ServiceReference1.ServiceSoap.getmobilebulk(BLL.ServiceReference1.getmobilebulkRequest request) {
            return base.Channel.getmobilebulk(request);
        }
        
        public string getmobilebulk(string appcode, string postcode, string citycode, string mode) {
            BLL.ServiceReference1.getmobilebulkRequest inValue = new BLL.ServiceReference1.getmobilebulkRequest();
            inValue.Body = new BLL.ServiceReference1.getmobilebulkRequestBody();
            inValue.Body.appcode = appcode;
            inValue.Body.postcode = postcode;
            inValue.Body.citycode = citycode;
            inValue.Body.mode = mode;
            BLL.ServiceReference1.getmobilebulkResponse retVal = ((BLL.ServiceReference1.ServiceSoap)(this)).getmobilebulk(inValue);
            return retVal.Body.getmobilebulkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.ServiceReference1.getgroupstrResponse BLL.ServiceReference1.ServiceSoap.getgroupstr(BLL.ServiceReference1.getgroupstrRequest request) {
            return base.Channel.getgroupstr(request);
        }
        
        public string getgroupstr(string appcode) {
            BLL.ServiceReference1.getgroupstrRequest inValue = new BLL.ServiceReference1.getgroupstrRequest();
            inValue.Body = new BLL.ServiceReference1.getgroupstrRequestBody();
            inValue.Body.appcode = appcode;
            BLL.ServiceReference1.getgroupstrResponse retVal = ((BLL.ServiceReference1.ServiceSoap)(this)).getgroupstr(inValue);
            return retVal.Body.getgroupstrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.ServiceReference1.getgroupmobilesResponse BLL.ServiceReference1.ServiceSoap.getgroupmobiles(BLL.ServiceReference1.getgroupmobilesRequest request) {
            return base.Channel.getgroupmobiles(request);
        }
        
        public string getgroupmobiles(string groupid, string appcode) {
            BLL.ServiceReference1.getgroupmobilesRequest inValue = new BLL.ServiceReference1.getgroupmobilesRequest();
            inValue.Body = new BLL.ServiceReference1.getgroupmobilesRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.appcode = appcode;
            BLL.ServiceReference1.getgroupmobilesResponse retVal = ((BLL.ServiceReference1.ServiceSoap)(this)).getgroupmobiles(inValue);
            return retVal.Body.getgroupmobilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.ServiceReference1.getgroupmobilesstrResponse BLL.ServiceReference1.ServiceSoap.getgroupmobilesstr(BLL.ServiceReference1.getgroupmobilesstrRequest request) {
            return base.Channel.getgroupmobilesstr(request);
        }
        
        public string getgroupmobilesstr(string groupid, string appcode) {
            BLL.ServiceReference1.getgroupmobilesstrRequest inValue = new BLL.ServiceReference1.getgroupmobilesstrRequest();
            inValue.Body = new BLL.ServiceReference1.getgroupmobilesstrRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.appcode = appcode;
            BLL.ServiceReference1.getgroupmobilesstrResponse retVal = ((BLL.ServiceReference1.ServiceSoap)(this)).getgroupmobilesstr(inValue);
            return retVal.Body.getgroupmobilesstrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.ServiceReference1.getgroupcountResponse BLL.ServiceReference1.ServiceSoap.getgroupcount(BLL.ServiceReference1.getgroupcountRequest request) {
            return base.Channel.getgroupcount(request);
        }
        
        public string getgroupcount(string groupid, string appcode) {
            BLL.ServiceReference1.getgroupcountRequest inValue = new BLL.ServiceReference1.getgroupcountRequest();
            inValue.Body = new BLL.ServiceReference1.getgroupcountRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.appcode = appcode;
            BLL.ServiceReference1.getgroupcountResponse retVal = ((BLL.ServiceReference1.ServiceSoap)(this)).getgroupcount(inValue);
            return retVal.Body.getgroupcountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.ServiceReference1.SendSMSResponse BLL.ServiceReference1.ServiceSoap.SendSMS(BLL.ServiceReference1.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(string username, string password, string text, string mobileno, string pnlno) {
            BLL.ServiceReference1.SendSMSRequest inValue = new BLL.ServiceReference1.SendSMSRequest();
            inValue.Body = new BLL.ServiceReference1.SendSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            inValue.Body.pnlno = pnlno;
            BLL.ServiceReference1.SendSMSResponse retVal = ((BLL.ServiceReference1.ServiceSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.ServiceReference1.RemainSmsResponse BLL.ServiceReference1.ServiceSoap.RemainSms(BLL.ServiceReference1.RemainSmsRequest request) {
            return base.Channel.RemainSms(request);
        }
        
        public string RemainSms(string username, string password) {
            BLL.ServiceReference1.RemainSmsRequest inValue = new BLL.ServiceReference1.RemainSmsRequest();
            inValue.Body = new BLL.ServiceReference1.RemainSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            BLL.ServiceReference1.RemainSmsResponse retVal = ((BLL.ServiceReference1.ServiceSoap)(this)).RemainSms(inValue);
            return retVal.Body.RemainSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.ServiceReference1.Send1smsResponse BLL.ServiceReference1.ServiceSoap.Send1sms(BLL.ServiceReference1.Send1smsRequest request) {
            return base.Channel.Send1sms(request);
        }
        
        public string Send1sms(string username, string text, string mobileno) {
            BLL.ServiceReference1.Send1smsRequest inValue = new BLL.ServiceReference1.Send1smsRequest();
            inValue.Body = new BLL.ServiceReference1.Send1smsRequestBody();
            inValue.Body.username = username;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            BLL.ServiceReference1.Send1smsResponse retVal = ((BLL.ServiceReference1.ServiceSoap)(this)).Send1sms(inValue);
            return retVal.Body.Send1smsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.ServiceReference1.Send1BulkResponse BLL.ServiceReference1.ServiceSoap.Send1Bulk(BLL.ServiceReference1.Send1BulkRequest request) {
            return base.Channel.Send1Bulk(request);
        }
        
        public string Send1Bulk(string username, string text, string mobileno) {
            BLL.ServiceReference1.Send1BulkRequest inValue = new BLL.ServiceReference1.Send1BulkRequest();
            inValue.Body = new BLL.ServiceReference1.Send1BulkRequestBody();
            inValue.Body.username = username;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            BLL.ServiceReference1.Send1BulkResponse retVal = ((BLL.ServiceReference1.ServiceSoap)(this)).Send1Bulk(inValue);
            return retVal.Body.Send1BulkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.ServiceReference1.getcitymobilesResponse BLL.ServiceReference1.ServiceSoap.getcitymobiles(BLL.ServiceReference1.getcitymobilesRequest request) {
            return base.Channel.getcitymobiles(request);
        }
        
        public string getcitymobiles(string cityid, int mode) {
            BLL.ServiceReference1.getcitymobilesRequest inValue = new BLL.ServiceReference1.getcitymobilesRequest();
            inValue.Body = new BLL.ServiceReference1.getcitymobilesRequestBody();
            inValue.Body.cityid = cityid;
            inValue.Body.mode = mode;
            BLL.ServiceReference1.getcitymobilesResponse retVal = ((BLL.ServiceReference1.ServiceSoap)(this)).getcitymobiles(inValue);
            return retVal.Body.getcitymobilesResult;
        }
    }
}
