#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAYADATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="payazobnet")]
	public partial class DataLinqpowerjackDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertmpowerindex(mpowerindex instance);
    partial void Updatempowerindex(mpowerindex instance);
    partial void Deletempowerindex(mpowerindex instance);
    #endregion
		
		public DataLinqpowerjackDataContext() : 
				base(global::PAYADATA.Properties.Settings.Default.payazobnetConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinqpowerjackDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinqpowerjackDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinqpowerjackDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinqpowerjackDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<mconsumelectrical> mconsumelectricals
		{
			get
			{
				return this.GetTable<mconsumelectrical>();
			}
		}
		
		public System.Data.Linq.Table<mpowerindex> mpowerindexes
		{
			get
			{
				return this.GetTable<mpowerindex>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mconsumelectrical")]
	public partial class mconsumelectrical
	{
		
		private int _xid;
		
		private System.Nullable<int> _xperiod;
		
		private string _xsteelpowerconsumption;
		
		private string _xamounelectricity;
		
		private string _xfinedamountofreactive;
		
		private string _xreactivepowerconsumption;
		
		private string _Xincreasedymand;
		
		private string _xamountfinesdymand;
		
		private string _xamountofpowerconsumed;
		
		private string _consumption;
		
		private string _xsavings;
		
		private string _xstartdate;
		
		private string _xtodate;
		
		public mconsumelectrical()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xid", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int xid
		{
			get
			{
				return this._xid;
			}
			set
			{
				if ((this._xid != value))
				{
					this._xid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xperiod", DbType="Int")]
		public System.Nullable<int> xperiod
		{
			get
			{
				return this._xperiod;
			}
			set
			{
				if ((this._xperiod != value))
				{
					this._xperiod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xsteelpowerconsumption", DbType="NVarChar(50)")]
		public string xsteelpowerconsumption
		{
			get
			{
				return this._xsteelpowerconsumption;
			}
			set
			{
				if ((this._xsteelpowerconsumption != value))
				{
					this._xsteelpowerconsumption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xamounelectricity", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string xamounelectricity
		{
			get
			{
				return this._xamounelectricity;
			}
			set
			{
				if ((this._xamounelectricity != value))
				{
					this._xamounelectricity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xfinedamountofreactive", DbType="NVarChar(50)")]
		public string xfinedamountofreactive
		{
			get
			{
				return this._xfinedamountofreactive;
			}
			set
			{
				if ((this._xfinedamountofreactive != value))
				{
					this._xfinedamountofreactive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xreactivepowerconsumption", DbType="NVarChar(50)")]
		public string xreactivepowerconsumption
		{
			get
			{
				return this._xreactivepowerconsumption;
			}
			set
			{
				if ((this._xreactivepowerconsumption != value))
				{
					this._xreactivepowerconsumption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Xincreasedymand", DbType="NVarChar(50)")]
		public string Xincreasedymand
		{
			get
			{
				return this._Xincreasedymand;
			}
			set
			{
				if ((this._Xincreasedymand != value))
				{
					this._Xincreasedymand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xamountfinesdymand", DbType="NVarChar(50)")]
		public string xamountfinesdymand
		{
			get
			{
				return this._xamountfinesdymand;
			}
			set
			{
				if ((this._xamountfinesdymand != value))
				{
					this._xamountfinesdymand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xamountofpowerconsumed", DbType="NVarChar(50)")]
		public string xamountofpowerconsumed
		{
			get
			{
				return this._xamountofpowerconsumed;
			}
			set
			{
				if ((this._xamountofpowerconsumed != value))
				{
					this._xamountofpowerconsumed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consumption", DbType="NVarChar(50)")]
		public string consumption
		{
			get
			{
				return this._consumption;
			}
			set
			{
				if ((this._consumption != value))
				{
					this._consumption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xsavings", DbType="NVarChar(50)")]
		public string xsavings
		{
			get
			{
				return this._xsavings;
			}
			set
			{
				if ((this._xsavings != value))
				{
					this._xsavings = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xstartdate", DbType="NChar(10)")]
		public string xstartdate
		{
			get
			{
				return this._xstartdate;
			}
			set
			{
				if ((this._xstartdate != value))
				{
					this._xstartdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xtodate", DbType="NChar(10)")]
		public string xtodate
		{
			get
			{
				return this._xtodate;
			}
			set
			{
				if ((this._xtodate != value))
				{
					this._xtodate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mpowerindex")]
	public partial class mpowerindex : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _xid;
		
		private string _xindexname;
		
		private System.Nullable<int> _xindexid;
		
		private string _xindexprice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnxidChanging(int value);
    partial void OnxidChanged();
    partial void OnxindexnameChanging(string value);
    partial void OnxindexnameChanged();
    partial void OnxindexidChanging(System.Nullable<int> value);
    partial void OnxindexidChanged();
    partial void OnxindexpriceChanging(string value);
    partial void OnxindexpriceChanged();
    #endregion
		
		public mpowerindex()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int xid
		{
			get
			{
				return this._xid;
			}
			set
			{
				if ((this._xid != value))
				{
					this.OnxidChanging(value);
					this.SendPropertyChanging();
					this._xid = value;
					this.SendPropertyChanged("xid");
					this.OnxidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xindexname", DbType="NVarChar(50)")]
		public string xindexname
		{
			get
			{
				return this._xindexname;
			}
			set
			{
				if ((this._xindexname != value))
				{
					this.OnxindexnameChanging(value);
					this.SendPropertyChanging();
					this._xindexname = value;
					this.SendPropertyChanged("xindexname");
					this.OnxindexnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xindexid", DbType="Int")]
		public System.Nullable<int> xindexid
		{
			get
			{
				return this._xindexid;
			}
			set
			{
				if ((this._xindexid != value))
				{
					this.OnxindexidChanging(value);
					this.SendPropertyChanging();
					this._xindexid = value;
					this.SendPropertyChanged("xindexid");
					this.OnxindexidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xindexprice", DbType="NVarChar(50)")]
		public string xindexprice
		{
			get
			{
				return this._xindexprice;
			}
			set
			{
				if ((this._xindexprice != value))
				{
					this.OnxindexpriceChanging(value);
					this.SendPropertyChanging();
					this._xindexprice = value;
					this.SendPropertyChanged("xindexprice");
					this.OnxindexpriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
