<?xml version="1.0" encoding="utf-8"?><Database Name="payazobnet" Class="data_name_operatorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.15.65;Initial Catalog=payazobnet;Persist Security Info=True;User ID=sa" SettingsObjectName="PAYADATA.Properties.Settings" SettingsPropertyName="payazobnetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.mworkergroup" Member="mworkergroups">
    <Type Name="mworkergroup">
      <Column Name="xnamegroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="xid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.mworker" Member="mworkers">
    <Type Name="mworker">
      <Column Name="xid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="xname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="xwork" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="xgroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>