#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAYADATA.disposal_object
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="payazobnet")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertmobject_disposal(mobject_disposal instance);
    partial void Updatemobject_disposal(mobject_disposal instance);
    partial void Deletemobject_disposal(mobject_disposal instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::PAYADATA.Properties.Settings.Default.payazobnetConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<mobject_disposal> mobject_disposals
		{
			get
			{
				return this.GetTable<mobject_disposal>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mobject_disposal")]
	public partial class mobject_disposal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _xid;
		
		private int _xid_interupt;
		
		private string _x_cod_objects_disposal;
		
		private System.Nullable<int> _xcount;
		
		private string _xtype;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnxidChanging(int value);
    partial void OnxidChanged();
    partial void Onxid_interuptChanging(int value);
    partial void Onxid_interuptChanged();
    partial void Onx_cod_objects_disposalChanging(string value);
    partial void Onx_cod_objects_disposalChanged();
    partial void OnxcountChanging(System.Nullable<int> value);
    partial void OnxcountChanged();
    partial void OnxtypeChanging(string value);
    partial void OnxtypeChanged();
    #endregion
		
		public mobject_disposal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int xid
		{
			get
			{
				return this._xid;
			}
			set
			{
				if ((this._xid != value))
				{
					this.OnxidChanging(value);
					this.SendPropertyChanging();
					this._xid = value;
					this.SendPropertyChanged("xid");
					this.OnxidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xid_interupt", DbType="Int NOT NULL")]
		public int xid_interupt
		{
			get
			{
				return this._xid_interupt;
			}
			set
			{
				if ((this._xid_interupt != value))
				{
					this.Onxid_interuptChanging(value);
					this.SendPropertyChanging();
					this._xid_interupt = value;
					this.SendPropertyChanged("xid_interupt");
					this.Onxid_interuptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_x_cod_objects_disposal", DbType="NVarChar(50)")]
		public string x_cod_objects_disposal
		{
			get
			{
				return this._x_cod_objects_disposal;
			}
			set
			{
				if ((this._x_cod_objects_disposal != value))
				{
					this.Onx_cod_objects_disposalChanging(value);
					this.SendPropertyChanging();
					this._x_cod_objects_disposal = value;
					this.SendPropertyChanged("x_cod_objects_disposal");
					this.Onx_cod_objects_disposalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xcount", DbType="Int")]
		public System.Nullable<int> xcount
		{
			get
			{
				return this._xcount;
			}
			set
			{
				if ((this._xcount != value))
				{
					this.OnxcountChanging(value);
					this.SendPropertyChanging();
					this._xcount = value;
					this.SendPropertyChanged("xcount");
					this.OnxcountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xtype", DbType="NChar(10)")]
		public string xtype
		{
			get
			{
				return this._xtype;
			}
			set
			{
				if ((this._xtype != value))
				{
					this.OnxtypeChanging(value);
					this.SendPropertyChanging();
					this._xtype = value;
					this.SendPropertyChanged("xtype");
					this.OnxtypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
