#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAYAIND.datalinq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="payazobnet")]
	public partial class kwhlinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertmasraf_zob(masraf_zob instance);
    partial void Updatemasraf_zob(masraf_zob instance);
    partial void Deletemasraf_zob(masraf_zob instance);
    partial void Insertmasraf_day(masraf_day instance);
    partial void Updatemasraf_day(masraf_day instance);
    partial void Deletemasraf_day(masraf_day instance);
    #endregion
		
		public kwhlinqDataContext() : 
				base(global::PAYAIND.Properties.Settings.Default.payazobnetConnectionString871316673, mappingSource)
		{
			OnCreated();
		}
		
		public kwhlinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public kwhlinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public kwhlinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public kwhlinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<masraf_zob> masraf_zobs
		{
			get
			{
				return this.GetTable<masraf_zob>();
			}
		}
		
		public System.Data.Linq.Table<masraf_day> masraf_days
		{
			get
			{
				return this.GetTable<masraf_day>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.masraf_zob")]
	public partial class masraf_zob : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _data;
		
		private string _shift;
		
		private System.Nullable<float> _kwh;
		
		private System.Nullable<float> _zob;
		
		private System.Nullable<float> _kwhpzob;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndataChanging(string value);
    partial void OndataChanged();
    partial void OnshiftChanging(string value);
    partial void OnshiftChanged();
    partial void OnkwhChanging(System.Nullable<float> value);
    partial void OnkwhChanged();
    partial void OnzobChanging(System.Nullable<float> value);
    partial void OnzobChanged();
    partial void OnkwhpzobChanging(System.Nullable<float> value);
    partial void OnkwhpzobChanged();
    #endregion
		
		public masraf_zob()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shift", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string shift
		{
			get
			{
				return this._shift;
			}
			set
			{
				if ((this._shift != value))
				{
					this.OnshiftChanging(value);
					this.SendPropertyChanging();
					this._shift = value;
					this.SendPropertyChanged("shift");
					this.OnshiftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kwh", DbType="Real")]
		public System.Nullable<float> kwh
		{
			get
			{
				return this._kwh;
			}
			set
			{
				if ((this._kwh != value))
				{
					this.OnkwhChanging(value);
					this.SendPropertyChanging();
					this._kwh = value;
					this.SendPropertyChanged("kwh");
					this.OnkwhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zob", DbType="Real")]
		public System.Nullable<float> zob
		{
			get
			{
				return this._zob;
			}
			set
			{
				if ((this._zob != value))
				{
					this.OnzobChanging(value);
					this.SendPropertyChanging();
					this._zob = value;
					this.SendPropertyChanged("zob");
					this.OnzobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kwhpzob", DbType="Real")]
		public System.Nullable<float> kwhpzob
		{
			get
			{
				return this._kwhpzob;
			}
			set
			{
				if ((this._kwhpzob != value))
				{
					this.OnkwhpzobChanging(value);
					this.SendPropertyChanging();
					this._kwhpzob = value;
					this.SendPropertyChanged("kwhpzob");
					this.OnkwhpzobChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.masraf_day")]
	public partial class masraf_day : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _date;
		
		private System.Nullable<float> _kwh;
		
		private System.Nullable<float> _pro;
		
		private System.Nullable<float> _kwhppro;
		
		private string _nameghete;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndateChanging(string value);
    partial void OndateChanged();
    partial void OnkwhChanging(System.Nullable<float> value);
    partial void OnkwhChanged();
    partial void OnproChanging(System.Nullable<float> value);
    partial void OnproChanged();
    partial void OnkwhpproChanging(System.Nullable<float> value);
    partial void OnkwhpproChanged();
    partial void OnnamegheteChanging(string value);
    partial void OnnamegheteChanged();
    #endregion
		
		public masraf_day()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kwh", DbType="Real")]
		public System.Nullable<float> kwh
		{
			get
			{
				return this._kwh;
			}
			set
			{
				if ((this._kwh != value))
				{
					this.OnkwhChanging(value);
					this.SendPropertyChanging();
					this._kwh = value;
					this.SendPropertyChanged("kwh");
					this.OnkwhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro", DbType="Real")]
		public System.Nullable<float> pro
		{
			get
			{
				return this._pro;
			}
			set
			{
				if ((this._pro != value))
				{
					this.OnproChanging(value);
					this.SendPropertyChanging();
					this._pro = value;
					this.SendPropertyChanged("pro");
					this.OnproChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kwhppro", DbType="Real")]
		public System.Nullable<float> kwhppro
		{
			get
			{
				return this._kwhppro;
			}
			set
			{
				if ((this._kwhppro != value))
				{
					this.OnkwhpproChanging(value);
					this.SendPropertyChanging();
					this._kwhppro = value;
					this.SendPropertyChanged("kwhppro");
					this.OnkwhpproChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameghete", DbType="NVarChar(50)")]
		public string nameghete
		{
			get
			{
				return this._nameghete;
			}
			set
			{
				if ((this._nameghete != value))
				{
					this.OnnamegheteChanging(value);
					this.SendPropertyChanging();
					this._nameghete = value;
					this.SendPropertyChanged("nameghete");
					this.OnnamegheteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
