#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLQ.DestructionReport
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Payazob")]
	public partial class DataClasses_DestructionReportsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertmDestructionReport(mDestructionReport instance);
    partial void UpdatemDestructionReport(mDestructionReport instance);
    partial void DeletemDestructionReport(mDestructionReport instance);
    #endregion
		
		public DataClasses_DestructionReportsDataContext() : 
				base(global::DLQ.Properties.Settings.Default.PayazobConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_DestructionReportsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_DestructionReportsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_DestructionReportsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses_DestructionReportsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<mDestructionReport> mDestructionReports
		{
			get
			{
				return this.GetTable<mDestructionReport>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateDestructionReport")]
		public int UpdateDestructionReport([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> x_, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string xDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> xShift_, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string xDateProduction, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> xPiceces_, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> xCount, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string xGrindingPlace, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(4,2)")] System.Nullable<decimal> xDepth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> xResult, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string xComment, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> xApprove_)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), x_, xDate, xShift_, xDateProduction, xPiceces_, xCount, xGrindingPlace, xDepth, xResult, xComment, xApprove_);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectDestructionReportByDate")]
		public ISingleResult<mDestructionReport> SelectDestructionReportByDate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateFrom", DbType="Char(10)")] string dateFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateTo", DbType="Char(10)")] string dateTo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dateFrom, dateTo);
			return ((ISingleResult<mDestructionReport>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mDestructionReport")]
	public partial class mDestructionReport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _x_;
		
		private string _xDate;
		
		private string _xDateProduction;
		
		private System.Nullable<int> _xPieces_;
		
		private System.Nullable<int> _xCount;
		
		private System.Nullable<int> _xTractionTest;
		
		private System.Nullable<int> _xTensionTest;
		
		private string _xGrindingPlace;
		
		private string _xDefect;
		
		private System.Nullable<int> _xGprResult_;
		
		private System.Nullable<int> _xApprove_;
		
		private System.Nullable<decimal> _xDepth;
		
		private string _xComment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onx_Changing(int value);
    partial void Onx_Changed();
    partial void OnxDateChanging(string value);
    partial void OnxDateChanged();
    partial void OnxDateProductionChanging(string value);
    partial void OnxDateProductionChanged();
    partial void OnxPieces_Changing(System.Nullable<int> value);
    partial void OnxPieces_Changed();
    partial void OnxCountChanging(System.Nullable<int> value);
    partial void OnxCountChanged();
    partial void OnxTractionTestChanging(System.Nullable<int> value);
    partial void OnxTractionTestChanged();
    partial void OnxTensionTestChanging(System.Nullable<int> value);
    partial void OnxTensionTestChanged();
    partial void OnxGrindingPlaceChanging(string value);
    partial void OnxGrindingPlaceChanged();
    partial void OnxDefectChanging(string value);
    partial void OnxDefectChanged();
    partial void OnxGprResult_Changing(System.Nullable<int> value);
    partial void OnxGprResult_Changed();
    partial void OnxApprove_Changing(System.Nullable<int> value);
    partial void OnxApprove_Changed();
    partial void OnxDepthChanging(System.Nullable<decimal> value);
    partial void OnxDepthChanged();
    partial void OnxCommentChanging(string value);
    partial void OnxCommentChanged();
    #endregion
		
		public mDestructionReport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_x_", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int x_
		{
			get
			{
				return this._x_;
			}
			set
			{
				if ((this._x_ != value))
				{
					this.Onx_Changing(value);
					this.SendPropertyChanging();
					this._x_ = value;
					this.SendPropertyChanged("x_");
					this.Onx_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xDate", DbType="Char(10)")]
		public string xDate
		{
			get
			{
				return this._xDate;
			}
			set
			{
				if ((this._xDate != value))
				{
					this.OnxDateChanging(value);
					this.SendPropertyChanging();
					this._xDate = value;
					this.SendPropertyChanged("xDate");
					this.OnxDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xDateProduction", DbType="Char(10)")]
		public string xDateProduction
		{
			get
			{
				return this._xDateProduction;
			}
			set
			{
				if ((this._xDateProduction != value))
				{
					this.OnxDateProductionChanging(value);
					this.SendPropertyChanging();
					this._xDateProduction = value;
					this.SendPropertyChanged("xDateProduction");
					this.OnxDateProductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xPieces_", DbType="Int")]
		public System.Nullable<int> xPieces_
		{
			get
			{
				return this._xPieces_;
			}
			set
			{
				if ((this._xPieces_ != value))
				{
					this.OnxPieces_Changing(value);
					this.SendPropertyChanging();
					this._xPieces_ = value;
					this.SendPropertyChanged("xPieces_");
					this.OnxPieces_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xCount", DbType="Int")]
		public System.Nullable<int> xCount
		{
			get
			{
				return this._xCount;
			}
			set
			{
				if ((this._xCount != value))
				{
					this.OnxCountChanging(value);
					this.SendPropertyChanging();
					this._xCount = value;
					this.SendPropertyChanged("xCount");
					this.OnxCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xTractionTest", DbType="Int")]
		public System.Nullable<int> xTractionTest
		{
			get
			{
				return this._xTractionTest;
			}
			set
			{
				if ((this._xTractionTest != value))
				{
					this.OnxTractionTestChanging(value);
					this.SendPropertyChanging();
					this._xTractionTest = value;
					this.SendPropertyChanged("xTractionTest");
					this.OnxTractionTestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xTensionTest", DbType="Int")]
		public System.Nullable<int> xTensionTest
		{
			get
			{
				return this._xTensionTest;
			}
			set
			{
				if ((this._xTensionTest != value))
				{
					this.OnxTensionTestChanging(value);
					this.SendPropertyChanging();
					this._xTensionTest = value;
					this.SendPropertyChanged("xTensionTest");
					this.OnxTensionTestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xGrindingPlace", DbType="NVarChar(50)")]
		public string xGrindingPlace
		{
			get
			{
				return this._xGrindingPlace;
			}
			set
			{
				if ((this._xGrindingPlace != value))
				{
					this.OnxGrindingPlaceChanging(value);
					this.SendPropertyChanging();
					this._xGrindingPlace = value;
					this.SendPropertyChanged("xGrindingPlace");
					this.OnxGrindingPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xDefect", DbType="NVarChar(500)")]
		public string xDefect
		{
			get
			{
				return this._xDefect;
			}
			set
			{
				if ((this._xDefect != value))
				{
					this.OnxDefectChanging(value);
					this.SendPropertyChanging();
					this._xDefect = value;
					this.SendPropertyChanged("xDefect");
					this.OnxDefectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xGprResult_", DbType="Int")]
		public System.Nullable<int> xGprResult_
		{
			get
			{
				return this._xGprResult_;
			}
			set
			{
				if ((this._xGprResult_ != value))
				{
					this.OnxGprResult_Changing(value);
					this.SendPropertyChanging();
					this._xGprResult_ = value;
					this.SendPropertyChanged("xGprResult_");
					this.OnxGprResult_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xApprove_", DbType="Int")]
		public System.Nullable<int> xApprove_
		{
			get
			{
				return this._xApprove_;
			}
			set
			{
				if ((this._xApprove_ != value))
				{
					this.OnxApprove_Changing(value);
					this.SendPropertyChanging();
					this._xApprove_ = value;
					this.SendPropertyChanged("xApprove_");
					this.OnxApprove_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xDepth", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> xDepth
		{
			get
			{
				return this._xDepth;
			}
			set
			{
				if ((this._xDepth != value))
				{
					this.OnxDepthChanging(value);
					this.SendPropertyChanging();
					this._xDepth = value;
					this.SendPropertyChanged("xDepth");
					this.OnxDepthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xComment", DbType="NVarChar(500)")]
		public string xComment
		{
			get
			{
				return this._xComment;
			}
			set
			{
				if ((this._xComment != value))
				{
					this.OnxCommentChanging(value);
					this.SendPropertyChanging();
					this._xComment = value;
					this.SendPropertyChanged("xComment");
					this.OnxCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
